var bbSet = [
  {
    "name":"Alarm Clock",
    "symbol":"bb-alarm-clock",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Bar Chart",
    "symbol":"bb-bar-chart",
    "category":"Business",
    "keywords":"Business",
    "set":"bb10"
  },
  {
    "name":"Barrel",
    "symbol":"bb-barrel",
    "category":"Food",
    "keywords":"Food",
    "set":"bb10"
  },
  {
    "name":"Battery",
    "symbol":"bb-battery",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"BBM",
    "symbol":"bb-bbm",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"BB Logo",
    "symbol":"bb-bbry-logo",
    "category":"Business",
    "keywords":"Business",
    "set":"bb10"
  },
  {
    "name":"Binders",
    "symbol":"bb-binders",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Bluetooth",
    "symbol":"bb-bluetooth",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Bookmark",
    "symbol":"bb-bookmark",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Bookmark Plus",
    "symbol":"bb-bookmark-plus",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Box",
    "symbol":"bb-box-closed",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Box",
    "symbol":"bb-box-open",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Briefcase",
    "symbol":"bb-briefcase",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Buggy",
    "symbol":"bb-buggy",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Bullseye",
    "symbol":"bb-bullseye",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Calculator",
    "symbol":"bb-calculator",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Calendar",
    "symbol":"bb-calendar",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Calendar Plus",
    "symbol":"bb-calendar-plus",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Incoming Call",
    "symbol":"bb-call-incoming",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Outgoing Call",
    "symbol":"bb-call-outgoing",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Returned Call",
    "symbol":"bb-call-returned",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Camera",
    "symbol":"bb-camera-still",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Video Camera",
    "symbol":"bb-camera-video",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Chat Bubble",
    "symbol":"bb-chat-bubble",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Checkmark",
    "symbol":"bb-checked",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Circle Arrow Down",
    "symbol":"bb-circle-arrow-down",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Circle Arrow Left",
    "symbol":"bb-circle-arrow-left",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Circle Arrow Right",
    "symbol":"bb-circle-arrow-right",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Circle Arrow Up",
    "symbol":"bb-circle-arrow-up",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Go Back",
    "symbol":"bb-circle-back",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Go to Beginning",
    "symbol":"bb-circle-beginning",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Dollar",
    "symbol":"bb-circle-dollar",
    "category":"Business",
    "keywords":"Business",
    "set":"bb10"
  },
  {
    "name":"Go to End",
    "symbol":"bb-circle-end",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Euro",
    "symbol":"bb-circle-euro",
    "category":"Business",
    "keywords":"Business",
    "set":"bb10"
  },
  {
    "name":"Facebook",
    "symbol":"bb-circle-facebook-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Flickr",
    "symbol":"bb-circle-flickr-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Forward",
    "symbol":"bb-circle-forward",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Google Plus",
    "symbol":"bb-circle-googleplus-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Info",
    "symbol":"bb-circle-info",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Info",
    "symbol":"bb-circle-info-1",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"LinkedIN",
    "symbol":"bb-circle-linkedin-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Next",
    "symbol":"bb-circle-next",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Open",
    "symbol":"bb-circle-open",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Pause",
    "symbol":"bb-circle-pause",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Pinterest",
    "symbol":"bb-circle-pinterest-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Play",
    "symbol":"bb-circle-play",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Play/Pause",
    "symbol":"bb-circle-play-pause",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Pound",
    "symbol":"bb-circle-pound",
    "category":"Business",
    "keywords":"Business",
    "set":"bb10"
  },
  {
    "name":"Previous",
    "symbol":"bb-circle-previous",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Question",
    "symbol":"bb-circle-question",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Record",
    "symbol":"bb-circle-record",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"RSS",
    "symbol":"bb-circle-rss-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Stop",
    "symbol":"bb-circle-stop",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Twitter",
    "symbol":"bb-circle-twitter-bird-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Twitter",
    "symbol":"bb-circle-twitter-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Vimeo",
    "symbol":"bb-circle-vimeo-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"YouTube",
    "symbol":"bb-circle-youtube-o",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Clipboard",
    "symbol":"bb-clipboard",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Clock",
    "symbol":"bb-clock",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Close",
    "symbol":"bb-close",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Cloud",
    "symbol":"bb-cloud",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Cloud Download",
    "symbol":"bb-cloud-download",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Cloud Upload",
    "symbol":"bb-cloud-upload",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Compass",
    "symbol":"bb-compass",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Contacts",
    "symbol":"bb-contacts",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"BBM Contacts",
    "symbol":"bb-contacts-bbm",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Contacts Plus",
    "symbol":"bb-contacts-plus",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Credit Cards",
    "symbol":"bb-credit-cards",
    "category":"Business",
    "keywords":"Business",
    "set":"bb10"
  },
  {
    "name":"Desk Lamp",
    "symbol":"bb-desk-lamp",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Document",
    "symbol":"bb-document",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Eighth Notes",
    "symbol":"bb-eighth-notes",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Full Screen",
    "symbol":"bb-envelope-open",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Exit Full Screen",
    "symbol":"bb-exit-full-screen",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Exit Full Screen",
    "symbol":"bb-exit-full-screen-1",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Film Strip",
    "symbol":"bb-film-strip",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Flag",
    "symbol":"bb-flag-1",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Chequered flag",
    "symbol":"bb-flag-chequered-1",
    "category":"Sports",
    "keywords":"Sports",
    "set":"bb10"
  },
  {
    "name":"Chequered flag",
    "symbol":"bb-flag-chequered-2",
    "category":"Sports",
    "keywords":"Sports",
    "set":"bb10"
  },
  {
    "name":"Golf Flag",
    "symbol":"bb-flag-golf",
    "category":"Sports",
    "keywords":"Sports",
    "set":"bb10"
  },
  {
    "name":"Golf Green",
    "symbol":"bb-flag-golf-green",
    "category":"Sports",
    "keywords":"Sports",
    "set":"bb10"
  },
  {
    "name":"Folder Closed",
    "symbol":"bb-folder-closed",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Folder Open",
    "symbol":"bb-folder-open",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Font Size",
    "symbol":"bb-font-size",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Footprints",
    "symbol":"bb-footprints",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Fountain Pen",
    "symbol":"bb-fountain-pen",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Full Screen",
    "symbol":"bb-full-screen",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Glasses",
    "symbol":"bb-glasses-2",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Glasses",
    "symbol":"bb-glasses-3",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Gear",
    "symbol":"bb-gear",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Glasses",
    "symbol":"bb-glasses-1",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Group",
    "symbol":"bb-group",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Hand Truck",
    "symbol":"bb-hand-truck",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Headphones",
    "symbol":"bb-headphones",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Heart",
    "symbol":"bb-heart",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Home",
    "symbol":"bb-home",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Home Plus",
    "symbol":"bb-home-plus",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Key",
    "symbol":"bb-key",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Utensils",
    "symbol":"bb-knife-fork",
    "category":"Food",
    "keywords":"Food",
    "set":"bb10"
  },
  {
    "name":"Place Setting",
    "symbol":"bb-knife-fork-plate",
    "category":"Food",
    "keywords":"Food",
    "set":"bb10"
  },
  {
    "name":"iPod",
    "symbol":"bb-layer-10",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Web Link",
    "symbol":"bb-link1",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Web Link",
    "symbol":"bb-link2",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Locked",
    "symbol":"bb-locked",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Magic 8 Ball",
    "symbol":"bb-magic8-ball",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Magnifying Glass",
    "symbol":"bb-magnifying-glass",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Mail",
    "symbol":"bb-mail",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Man",
    "symbol":"bb-man-turtleneck",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Man",
    "symbol":"bb-man-vneck",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Map Marker",
    "symbol":"bb-map-marker",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Megaphone",
    "symbol":"bb-megaphone",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Main Menu",
    "symbol":"bb-main-menu",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Menu Overflow",
    "symbol":"bb-menu-overflow",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Retro Mic",
    "symbol":"bb-mic-retro",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Mobile",
    "symbol":"bb-mobile",
    "category":"Technology",
    "keywords":"Technology, Social",
    "set":"bb10"
  },
  {
    "name":"Monitor",
    "symbol":"bb-monitor",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Moon & Stars",
    "symbol":"bb-moon-stars",
    "category":"Nature",
    "keywords":"Nature",
    "set":"bb10"
  },
  {
    "name":"Motorcycle",
    "symbol":"bb-motor-bike",
    "category":"Travel",
    "keywords":"Travel",
    "set":"bb10"
  },
  {
    "name":"No Entry",
    "symbol":"bb-no-entry",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Notification",
    "symbol":"bb-notification",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Paint Brush",
    "symbol":"bb-paint-brush",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Paint Bucket",
    "symbol":"bb-paint-bucket",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Paint Palette",
    "symbol":"bb-paint-pallett",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Pawprint",
    "symbol":"bb-pawprint",
    "category":"Nature",
    "keywords":"Nature",
    "set":"bb10"
  },
  {
    "name":"Pencil",
    "symbol":"bb-pencil",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Photos",
    "symbol":"bb-photos",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Piano Keys",
    "symbol":"bb-piano-keys",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Pie Chart",
    "symbol":"bb-pie-chart",
    "category":"Business",
    "keywords":"Business",
    "set":"bb10"
  },
  {
    "name":"Poaroid",
    "symbol":"bb-polaroid-tulip",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Printer",
    "symbol":"bb-printer",
    "category":"Office",
    "keywords":"Office, Technology",
    "set":"bb10"
  },
  {
    "name":"Radio",
    "symbol":"bb-radio",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Refresh",
    "symbol":"bb-refresh",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Reload",
    "symbol":"bb-reload",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Reply",
    "symbol":"bb-reply",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Ring Buoy",
    "symbol":"bb-ring-buoy",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Roller Blade",
    "symbol":"bb-roller-blade",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Sciissors",
    "symbol":"bb-scissors",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Scooter",
    "symbol":"bb-scooter",
    "category":"Travel",
    "keywords":"Travel",
    "set":"bb10"
  },
  {
    "name":"Screen",
    "symbol":"bb-screen",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Send",
    "symbol":"bb-send",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Server",
    "symbol":"bb-server",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Shamrock",
    "symbol":"bb-shamrock",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Share",
    "symbol":"bb-share",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Signal",
    "symbol":"bb-signal",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Signs",
    "symbol":"bb-signs",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"RSS",
    "symbol":"bb-rss",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"BB Spark",
    "symbol":"bb-circle-spark",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Back",
    "symbol":"bb-square-back",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Beginning",
    "symbol":"bb-square-beginning",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"End",
    "symbol":"bb-square-end",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Facebook",
    "symbol":"bb-square-facebook",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Flickr",
    "symbol":"bb-square-flickr",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Forward",
    "symbol":"bb-square-forward",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Goolge Plus",
    "symbol":"bb-square-googleplus",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Web Link",
    "symbol":"bb-square-link",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"LinkedIN",
    "symbol":"bb-square-linkedin",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Next",
    "symbol":"bb-square-next",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Open",
    "symbol":"bb-square-open",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Pause",
    "symbol":"bb-square-pause",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Pinterest",
    "symbol":"bb-square-pinterest",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Play",
    "symbol":"bb-square-play",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Previous",
    "symbol":"bb-square-previous",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Record",
    "symbol":"bb-square-record",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Repeat",
    "symbol":"bb-square-repeat",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"RSS",
    "symbol":"bb-square-rss",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Shuffle",
    "symbol":"bb-square-shuffle",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Stop",
    "symbol":"bb-square-stop",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Twitter",
    "symbol":"bb-square-twitter",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Twitter",
    "symbol":"bb-square-twitter-bird",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Vimeo",
    "symbol":"bb-square-twitter-vimeo",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"YouTube",
    "symbol":"bb-square-youtube",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Star",
    "symbol":"bb-star",
    "category":"Nature",
    "keywords":"Nature",
    "set":"bb10"
  },
  {
    "name":"Sticky",
    "symbol":"bb-sticky",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Stop Sign",
    "symbol":"bb-stop-sign",
    "category":"Travel",
    "keywords":"Travel",
    "set":"bb10"
  },
  {
    "name":"Stop Watch",
    "symbol":"bb-stopwatch",
    "category":"Sports",
    "keywords":"Sports",
    "set":"bb10"
  },
  {
    "name":"Suitcase",
    "symbol":"bb-suitcase",
    "category":"Travel",
    "keywords":"Travel",
    "set":"bb10"
  },
  {
    "name":"Suitcase",
    "symbol":"bb-suitcase-wheels",
    "category":"Travel",
    "keywords":"Travel",
    "set":"bb10"
  },
  {
    "name":"Sun",
    "symbol":"bb-sun-1",
    "category":"Nature",
    "keywords":"Nature",
    "set":"bb10"
  },
  {
    "name":"Sun",
    "symbol":"bb-sun-2",
    "category":"Nature",
    "keywords":"Nature",
    "set":"bb10"
  },
  {
    "name":"Tag",
    "symbol":"bb-tag-1",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Tag",
    "symbol":"bb-tag-2",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Target",
    "symbol":"bb-target",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Thumbtack",
    "symbol":"bb-thumb-tack",
    "category":"Office",
    "keywords":"Office",
    "set":"bb10"
  },
  {
    "name":"Thumbs Down",
    "symbol":"bb-thumbs-down",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Thumbs Up",
    "symbol":"bb-thumbs-up",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Ticket",
    "symbol":"bb-ticket",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Trash",
    "symbol":"bb-trash",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Umbrella",
    "symbol":"bb-umbrella",
    "category":"Objects",
    "keywords":"Objects",
    "set":"bb10"
  },
  {
    "name":"Unlocked",
    "symbol":"bb-unlocked",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Update",
    "symbol":"bb-update",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Voicemail",
    "symbol":"bb-voicemail",
    "category":"Social",
    "keywords":"Social",
    "set":"bb10"
  },
  {
    "name":"Volume High",
    "symbol":"bb-vol-high",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Volume Low",
    "symbol":"bb-vol-low",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Volume Medium",
    "symbol":"bb-vol-med",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Mute",
    "symbol":"bb-vol-mute",
    "category":"Entertainment",
    "keywords":"Entertainment",
    "set":"bb10"
  },
  {
    "name":"Warning",
    "symbol":"bb-warning",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Wifi",
    "symbol":"bb-wifi",
    "category":"Technology",
    "keywords":"Technology",
    "set":"bb10"
  },
  {
    "name":"Woman",
    "symbol":"bb-woman-turtleneck",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Woman",
    "symbol":"bb-woman-vneck",
    "category":"People",
    "keywords":"People",
    "set":"bb10"
  },
  {
    "name":"Zoom In",
    "symbol":"bb-zoom-in",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  },
  {
    "name":"Zoom Out",
    "symbol":"bb-zoom-out",
    "category":"UI",
    "keywords":"UI",
    "set":"bb10"
  }
]