var faSetPlus = [
  {
    "name":"Glass",
    "symbol":"fa-glass",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"entertainment, food, drink, party "
  },
  {
    "name":"Music",
    "symbol":"fa-music",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"entertainment, music"
  },
  {
    "name":"Search",
    "symbol":"fa-search",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"ui, technology"
  },
  {
    "name":"Envelope",
    "symbol":"fa-envelope-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Heart",
    "symbol":"fa-heart",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Star",
    "symbol":"fa-star",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Star",
    "symbol":"fa-star-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"User",
    "symbol":"fa-user",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Film",
    "symbol":"fa-film",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Table Header",
    "symbol":"fa-th-large",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Table Header",
    "symbol":"fa-th",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"List",
    "symbol":"fa-th-list",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"OK",
    "symbol":"fa-check",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Close",
    "symbol":"fa-times",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Zoom In",
    "symbol":"fa-search-plus",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Zoom Out",
    "symbol":"fa-search-minus",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Power Off",
    "symbol":"fa-power-off",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Signal",
    "symbol":"fa-signal",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Cog",
    "symbol":"fa-cog",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Trash",
    "symbol":"fa-trash-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Home",
    "symbol":"fa-home",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"File",
    "symbol":"fa-file-o",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Clock",
    "symbol":"fa-clock-o",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Road",
    "symbol":"fa-road",
    "category":"Travel",
    "author":"font-awesome",
    "keywords":"Travel"
  },
  {
    "name":"Download",
    "symbol":"fa-download",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Arrow Down",
    "symbol":"fa-arrow-circle-o-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Arrow Up",
    "symbol":"fa-arrow-circle-o-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Inbox",
    "symbol":"fa-inbox",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Circle Play",
    "symbol":"fa-play-circle-o",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Repeat",
    "symbol":"fa-repeat",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Refresh",
    "symbol":"fa-refresh",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"List",
    "symbol":"fa-list-alt",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Lock",
    "symbol":"fa-lock",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Flag",
    "symbol":"fa-flag",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Headphones",
    "symbol":"fa-headphones",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Volume Off",
    "symbol":"fa-volume-off",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"entertainment, sound, media control"
  },
  {
    "name":"Volume Down",
    "symbol":"fa-volume-down",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"entertainment, sound, media control"
  },
  {
    "name":"Volume Up",
    "symbol":"fa-volume-up",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"entertainment, sound, media control"
  },
  {
    "name":"QR Code",
    "symbol":"fa-qrcode",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Bar Code",
    "symbol":"fa-barcode",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Tag",
    "symbol":"fa-tag",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Tags",
    "symbol":"fa-tags",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Book",
    "symbol":"fa-book",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Bookmark",
    "symbol":"fa-bookmark",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Print",
    "symbol":"fa-print",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Camera",
    "symbol":"fa-camera",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Font",
    "symbol":"fa-font",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Bold",
    "symbol":"fa-bold",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Italic",
    "symbol":"fa-italic",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Text Height",
    "symbol":"fa-text-height",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Text Width",
    "symbol":"fa-text-width",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Align Left",
    "symbol":"fa-align-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Align Center",
    "symbol":"fa-align-center",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Align Right",
    "symbol":"fa-align-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Align Justify",
    "symbol":"fa-align-justify",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"List",
    "symbol":"fa-list",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Indent",
    "symbol":"fa-indent",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Outdent",
    "symbol":"fa-outdent",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Camera Video",
    "symbol":"fa-video-camera",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Picture",
    "symbol":"fa-picture-o",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Pencil",
    "symbol":"fa-pencil",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Map Marker",
    "symbol":"fa-map-marker",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Adjust",
    "symbol":"fa-adjust",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Tint",
    "symbol":"fa-tint",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Pencil",
    "symbol":"fa-pencil-square-o",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Share",
    "symbol":"fa-share-square-o",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"OK",
    "symbol":"fa-check-square-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Move",
    "symbol":"fa-arrows",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Step Back",
    "symbol":"fa-step-backward",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Step Forward",
    "symbol":"fa-fast-backward",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Backward",
    "symbol":"fa-backward",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Play",
    "symbol":"fa-play",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Pause",
    "symbol":"fa-pause",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Stop",
    "symbol":"fa-stop",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Forward",
    "symbol":"fa-forward",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Fast Forward",
    "symbol":"fa-fast-forward",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Step Forward",
    "symbol":"fa-step-forward",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Eject",
    "symbol":"fa-eject",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Chevron Left",
    "symbol":"fa-chevron-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Chevron Right",
    "symbol":"fa-chevron-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Plus",
    "symbol":"fa-plus-circle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Minus",
    "symbol":"fa-minus-circle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Close",
    "symbol":"fa-times-circle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle OK",
    "symbol":"fa-check-circle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Question",
    "symbol":"fa-question-circle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Info",
    "symbol":"fa-info-circle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Crosshairs",
    "symbol":"fa-crosshairs",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Close",
    "symbol":"fa-times-circle-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle OK",
    "symbol":"fa-check-circle-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Ban",
    "symbol":"fa-ban",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrow Left",
    "symbol":"fa-arrow-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrow Right",
    "symbol":"fa-arrow-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrow Up",
    "symbol":"fa-arrow-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrow Down",
    "symbol":"fa-arrow-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Share",
    "symbol":"fa-share",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Expand",
    "symbol":"fa-expand",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Compress",
    "symbol":"fa-compress",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Add",
    "symbol":"fa-plus",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Subtract",
    "symbol":"fa-minus",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Multiply",
    "symbol":"fa-asterisk",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Circle Caution",
    "symbol":"fa-exclamation-circle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Gift",
    "symbol":"fa-gift",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Leaf",
    "symbol":"fa-leaf",
    "category":"Nature",
    "author":"font-awesome",
    "keywords":"Nature"
  },
  {
    "name":"Fire",
    "symbol":"fa-fire",
    "category":"Nature",
    "author":"font-awesome",
    "keywords":"Nature"
  },
  {
    "name":"Visible",
    "symbol":"fa-eye",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Not Visible",
    "symbol":"fa-eye-slash",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Caution",
    "symbol":"fa-exclamation-triangle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Plane",
    "symbol":"fa-plane",
    "category":"Travel",
    "author":"font-awesome",
    "keywords":"Travel"
  },
  {
    "name":"Calendar",
    "symbol":"fa-calendar",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Random",
    "symbol":"fa-random",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Comment",
    "symbol":"fa-comment",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Magnet",
    "symbol":"fa-magnet",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Chevron Up",
    "symbol":"fa-chevron-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Chevron Down",
    "symbol":"fa-chevron-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Retweet",
    "symbol":"fa-retweet",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Business Cart",
    "symbol":"fa-shopping-cart",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Folder",
    "symbol":"fa-folder",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Folder Open",
    "symbol":"fa-folder-open",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrows Vertical",
    "symbol":"fa-arrows-v",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrows Horizontal",
    "symbol":"fa-arrows-h",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Bar Chart",
    "symbol":"fa-bar-chart-o",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Twitter",
    "symbol":"fa-twitter-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Facebook",
    "symbol":"fa-facebook-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Camera",
    "symbol":"fa-camera-retro",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Key",
    "symbol":"fa-key",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Cogs",
    "symbol":"fa-cogs",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Comments",
    "symbol":"fa-comments",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Thumbs Up",
    "symbol":"fa-thumbs-o-up",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Thumbs Down",
    "symbol":"fa-thumbs-o-down",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Star Half",
    "symbol":"fa-star-half",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Heart",
    "symbol":"fa-heart-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sign Out",
    "symbol":"fa-sign-out",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"LinkedIN",
    "symbol":"fa-linkedin-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Thumbtack",
    "symbol":"fa-thumb-tack",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Link",
    "symbol":"fa-external-link",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sign In",
    "symbol":"fa-sign-in",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Trophy",
    "symbol":"fa-trophy",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Github",
    "symbol":"fa-github-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Upload",
    "symbol":"fa-upload",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Lemon",
    "symbol":"fa-lemon-o",
    "category":"Nature",
    "author":"font-awesome",
    "keywords":"Nature"
  },
  {
    "name":"Phone",
    "symbol":"fa-phone",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Square",
    "symbol":"fa-square-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Bookmark",
    "symbol":"fa-bookmark-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Phone",
    "symbol":"fa-phone-square",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Twitter",
    "symbol":"fa-twitter",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Facebook",
    "symbol":"fa-facebook",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Github",
    "symbol":"fa-github",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Unlock",
    "symbol":"fa-unlock",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Credit Card",
    "symbol":"fa-credit-card",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"RSS",
    "symbol":"fa-rss",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"HDD",
    "symbol":"fa-hdd-o",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Bullhorn",
    "symbol":"fa-bullhorn",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Bell",
    "symbol":"fa-bell",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Certificate",
    "symbol":"fa-certificate",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Hand right",
    "symbol":"fa-hand-o-right",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Hand left",
    "symbol":"fa-hand-o-left",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Hand up",
    "symbol":"fa-hand-o-up",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Hand down",
    "symbol":"fa-hand-o-down",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Circle Arrow Left",
    "symbol":"fa-arrow-circle-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Arrow Right",
    "symbol":"fa-arrow-circle-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Arrow Up",
    "symbol":"fa-arrow-circle-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Arrow Down",
    "symbol":"fa-arrow-circle-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Globe",
    "symbol":"fa-globe",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Wrench",
    "symbol":"fa-wrench",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Tasks",
    "symbol":"fa-tasks",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Filter",
    "symbol":"fa-filter",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Briefcase",
    "symbol":"fa-briefcase",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrows",
    "symbol":"fa-arrows-alt",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Users",
    "symbol":"fa-users",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Link",
    "symbol":"fa-link",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Cloud",
    "symbol":"fa-cloud",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Beaker",
    "symbol":"fa-flask",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Scissors",
    "symbol":"fa-scissors",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Files",
    "symbol":"fa-files-o",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Paperclip",
    "symbol":"fa-paperclip",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Floppy Disk",
    "symbol":"fa-floppy-o",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Square",
    "symbol":"fa-square",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Bars",
    "symbol":"fa-bars",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"List Unordered",
    "symbol":"fa-list-ul",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"List Ordered",
    "symbol":"fa-list-ol",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Strikethrough",
    "symbol":"fa-strikethrough",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Underline",
    "symbol":"fa-underline",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Table",
    "symbol":"fa-table",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Magic",
    "symbol":"fa-magic",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Truck",
    "symbol":"fa-truck",
    "category":"Travel",
    "author":"font-awesome",
    "keywords":"Travel"
  },
  {
    "name":"Pinterest",
    "symbol":"fa-pinterest",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Pinterest",
    "symbol":"fa-pinterest-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Goolge Plus",
    "symbol":"fa-google-plus-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Google Plus",
    "symbol":"fa-google-plus",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Business",
    "symbol":"fa-money",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Caret Down",
    "symbol":"fa-caret-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Caret Up",
    "symbol":"fa-caret-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Caret Left",
    "symbol":"fa-caret-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Caret Right",
    "symbol":"fa-caret-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Columns",
    "symbol":"fa-columns",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sort",
    "symbol":"fa-sort",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sort Down",
    "symbol":"fa-sort-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sort Up",
    "symbol":"fa-sort-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Envelope",
    "symbol":"fa-envelope",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"LinkedIN",
    "symbol":"fa-linkedin",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Undo",
    "symbol":"fa-undo",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Legal",
    "symbol":"fa-legal",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Dashboard",
    "symbol":"fa-dashboard",
    "category":"Travel",
    "author":"font-awesome",
    "keywords":"Travel"
  },
  {
    "name":"Comment",
    "symbol":"fa-comment-o",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Comments",
    "symbol":"fa-comments-o",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Bold",
    "symbol":"fa-bolt",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sitemap",
    "symbol":"fa-sitemap",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Umbrella",
    "symbol":"fa-umbrella",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Paste",
    "symbol":"fa-paste",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Lightbulb",
    "symbol":"fa-lightbulb-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Exchange",
    "symbol":"fa-exchange",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Cloud Download",
    "symbol":"fa-cloud-download",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Cloud Upload",
    "symbol":"fa-cloud-upload",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"User MD",
    "symbol":"fa-user-md",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Stethoscope",
    "symbol":"fa-stethoscope",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Suitecase",
    "symbol":"fa-suitcase",
    "category":"Travel",
    "author":"font-awesome",
    "keywords":"Travel"
  },
  {
    "name":"Bell",
    "symbol":"fa-bell-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Coffee",
    "symbol":"fa-coffee",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Cutlery",
    "symbol":"fa-cutlery",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Text File",
    "symbol":"fa-file-text-o",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Building",
    "symbol":"fa-building-o",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Hospital",
    "symbol":"fa-hospital-o",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Ambulance",
    "symbol":"fa-ambulance",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Medical Kit",
    "symbol":"fa-medkit",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Fighter Jet",
    "symbol":"fa-fighter-jet",
    "category":"Travel",
    "author":"font-awesome",
    "keywords":"Travel"
  },
  {
    "name":"Beer",
    "symbol":"fa-beer",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Square",
    "symbol":"fa-h-square",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Plus",
    "symbol":"fa-plus-square-o",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Angle Double Left",
    "symbol":"fa-angle-double-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Angle Double Right",
    "symbol":"fa-angle-double-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Angle Double Up",
    "symbol":"fa-angle-double-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Angle double Down",
    "symbol":"fa-angle-double-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Angle Left",
    "symbol":"fa-angle-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Angle Right",
    "symbol":"fa-angle-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Angle Up",
    "symbol":"fa-angle-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Angle Down",
    "symbol":"fa-angle-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Desktop",
    "symbol":"fa-desktop",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Laptop",
    "symbol":"fa-laptop",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Tablet",
    "symbol":"fa-tablet",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Mobile",
    "symbol":"fa-mobile-phone",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Circle",
    "symbol":"fa-circle-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Qutoe Left",
    "symbol":"fa-quote-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Quote Right",
    "symbol":"fa-quote-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Spinner",
    "symbol":"fa-spinner",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle",
    "symbol":"fa-circle",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Reply",
    "symbol":"fa-reply",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Github",
    "symbol":"fa-github-alt",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Folder",
    "symbol":"fa-folder-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Folder",
    "symbol":"fa-folder-open-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Smile ",
    "symbol":"fa-smile-o",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Frown",
    "symbol":"fa-frown-o",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Meh",
    "symbol":"fa-meh-o",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Gamepad",
    "symbol":"fa-gamepad",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Keyboard",
    "symbol":"fa-keyboard-o",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Flag",
    "symbol":"fa-flag-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Flag Checkerred",
    "symbol":"fa-flag-checkered",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Terminal",
    "symbol":"fa-terminal",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Code",
    "symbol":"fa-code",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Reply All",
    "symbol":"fa-reply-all",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Mail Reply All",
    "symbol":"fa-mail-reply-all",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Star Half",
    "symbol":"fa-star-half-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrow Location",
    "symbol":"fa-location-arrow",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Crop",
    "symbol":"fa-crop",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Fork Code",
    "symbol":"fa-code-fork",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Unlink",
    "symbol":"fa-unlink",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Question",
    "symbol":"fa-question",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Info",
    "symbol":"fa-info",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Exclamation",
    "symbol":"fa-exclamation",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Superscript",
    "symbol":"fa-superscript",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Subscript",
    "symbol":"fa-subscript",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Eraser",
    "symbol":"fa-eraser",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Puzzle Piece",
    "symbol":"fa-puzzle-piece",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Audio",
    "symbol":"fa-microphone",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Mute",
    "symbol":"fa-microphone-slash",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Shield",
    "symbol":"fa-shield",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Calendar",
    "symbol":"fa-calendar-o",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Fire Exttinguisher",
    "symbol":"fa-fire-extinguisher",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Rocket",
    "symbol":"fa-rocket",
    "category":"Travel",
    "author":"font-awesome",
    "keywords":"Travel"
  },
  {
    "name":"Max CDN",
    "symbol":"fa-maxcdn",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Circle Chevron Left",
    "symbol":"fa-chevron-circle-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Chevron Right",
    "symbol":"fa-chevron-circle-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Chevron Up",
    "symbol":"fa-chevron-circle-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Chevron Down",
    "symbol":"fa-chevron-circle-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"HTML5",
    "symbol":"fa-html5",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"CSS3",
    "symbol":"fa-css3",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Anchor ",
    "symbol":"fa-anchor",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Unlock",
    "symbol":"fa-unlock-alt",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Bullseye",
    "symbol":"fa-bullseye",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Ellipsis",
    "symbol":"fa-ellipsis-h",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Ellipsis",
    "symbol":"fa-ellipsis-v",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Ellipsis Vertical",
    "symbol":"fa-ellipsis-v",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"RSS",
    "symbol":"fa-rss-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Play",
    "symbol":"fa-play-circle",
    "category":"Entertainment",
    "author":"font-awesome",
    "keywords":"Entertainment"
  },
  {
    "name":"Ticket",
    "symbol":"fa-ticket",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Minus",
    "symbol":"fa-minus-square",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Minus",
    "symbol":"fa-minus-square-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Level Up",
    "symbol":"fa-level-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Level Down",
    "symbol":"fa-level-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"OK",
    "symbol":"fa-check-square",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Pencil",
    "symbol":"fa-pencil-square",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Link",
    "symbol":"fa-external-link-square",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Compass",
    "symbol":"fa-compass",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Share",
    "symbol":"fa-share-square",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Caret Square Up",
    "symbol":"fa-caret-square-o-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Caret Square Down",
    "symbol":"fa-caret-square-o-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Caret Square Right",
    "symbol":"fa-caret-square-o-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Euro",
    "symbol":"fa-eur",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"British Pound",
    "symbol":"fa-gbp",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"US Dollar",
    "symbol":"fa-usd",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Indian Rupee",
    "symbol":"fa-inr",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Japenese Yen",
    "symbol":"fa-jpy",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Chinese Yuan",
    "symbol":"fa-cny",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"So Korean Won",
    "symbol":"fa-krw",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Bitcoin",
    "symbol":"fa-btc",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"File",
    "symbol":"fa-file",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Document",
    "symbol":"fa-file-text",
    "category":"Business",
    "author":"font-awesome",
    "keywords":"Business"
  },
  {
    "name":"Sort Alpha Asc",
    "symbol":"fa-sort-alpha-asc",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sort Alpha Desc",
    "symbol":"fa-sort-alpha-desc",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sort Amount Asc",
    "symbol":"fa-sort-amount-asc",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sort Amount Desc",
    "symbol":"fa-sort-amount-desc",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sort Numeric Asc",
    "symbol":"fa-sort-numeric-asc",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Sort Numeric Desc",
    "symbol":"fa-sort-numeric-desc",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Thumbs Up",
    "symbol":"fa-thumbs-up",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Thumbs Down",
    "symbol":"fa-thumbs-down",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"YouTube",
    "symbol":"fa-youtube-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"YouTube",
    "symbol":"fa-youtube",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Xing",
    "symbol":"fa-xing",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Xing",
    "symbol":"fa-xing-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"YouTube Play",
    "symbol":"fa-youtube-play",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"DropBox",
    "symbol":"fa-dropbox",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Stack Overflow",
    "symbol":"fa-stack-overflow",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Instagram",
    "symbol":"fa-instagram",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Flickr",
    "symbol":"fa-flickr",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Ad-n",
    "symbol":"fa-adn",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"BitBucket",
    "symbol":"fa-bitbucket",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"BitBucket",
    "symbol":"fa-bitbucket-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Tumblr",
    "symbol":"fa-tumblr",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Tumblr",
    "symbol":"fa-tumblr-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Arrow Long Down",
    "symbol":"fa-long-arrow-down",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrow Long Up",
    "symbol":"fa-long-arrow-up",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrow Long Left",
    "symbol":"fa-long-arrow-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Arrow Long Right",
    "symbol":"fa-long-arrow-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Apple",
    "symbol":"fa-apple",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Windows",
    "symbol":"fa-windows",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Android",
    "symbol":"fa-android",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Linux",
    "symbol":"fa-linux",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Dribble",
    "symbol":"fa-dribbble",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Skype",
    "symbol":"fa-skype",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"FourSquare",
    "symbol":"fa-foursquare",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Trello",
    "symbol":"fa-trello",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Female",
    "symbol":"fa-female",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Male",
    "symbol":"fa-male",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"GitTip",
    "symbol":"fa-gittip",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Sun",
    "symbol":"fa-sun-o",
    "category":"Nature",
    "author":"font-awesome",
    "keywords":"Nature"
  },
  {
    "name":"Moon",
    "symbol":"fa-moon-o",
    "category":"Nature",
    "author":"font-awesome",
    "keywords":"Nature"
  },
  {
    "name":"Archive",
    "symbol":"fa-archive",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Bug",
    "symbol":"fa-bug",
    "category":"Technology",
    "author":"font-awesome",
    "keywords":"Technology"
  },
  {
    "name":"Vk",
    "symbol":"fa-vk",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Weibo",
    "symbol":"fa-weibo",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"RenRen",
    "symbol":"fa-renren",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"PageLines",
    "symbol":"fa-pagelines",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Stack Exchange",
    "symbol":"fa-stack-exchange",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Circle Arrow Right",
    "symbol":"fa-arrow-circle-o-right",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Arrow Left",
    "symbol":"fa-arrow-circle-o-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Square Caret Left",
    "symbol":"fa-caret-square-o-left",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Circle Dot",
    "symbol":"fa-dot-circle-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Wheelchair",
    "symbol":"fa-wheelchair",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Vimeo",
    "symbol":"fa-vimeo-square",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Try",
    "symbol":"fa-try",
    "category":"Social",
    "author":"font-awesome",
    "keywords":"Social"
  },
  {
    "name":"Square Plus",
    "symbol":"fa-plus-square-o",
    "category":"UI",
    "author":"font-awesome",
    "keywords":"UI"
  },
  {
    "name":"Popsicle",
    "symbol":"st-popsicle",
    "category":"Entertainment",
    "author":"streamline",
    "keywords":"Entertainment"
  },
  {
    "name":"Hotdog",
    "symbol":"st-hotdog",
    "category":"Entertainment",
    "author":"streamline",
    "keywords":"Entertainment"
  },
  {
    "name":"Knife & Fork",
    "symbol":"st-knife-fork",
    "category":"Entertainment",
    "author":"streamline",
    "keywords":"Entertainment"
  },
  {
    "name":"Chef Hat",
    "symbol":"st-hat-chef",
    "category":"Entertainment",
    "author":"streamline",
    "keywords":"Entertainment"
  },
  {
    "name":"Barbecue",
    "symbol":"st-barbecue",
    "category":"Entertainment",
    "author":"streamline",
    "keywords":"Entertainment"
  },
  {
    "name":"Bar chart",
    "symbol":"bb-bar-chart",
    "category":"Business",
    "author":"fontology",
    "keywords":"Business"
  },
  {
    "name":"Bookmark",
    "symbol":"bb-bookmark",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Calculator",
    "symbol":"bb-calculator",
    "category":"Business",
    "author":"fontology",
    "keywords":"Business"
  },
  {
    "name":"Mail ",
    "symbol":"bb-message-mail",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"BBM",
    "symbol":"bb-message-bbm",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Map Marker",
    "symbol":"bb-map-marker",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"SMS",
    "symbol":"bb-message-text",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Cloud Upload",
    "symbol":"bb-cloud-upload",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Cloud Download",
    "symbol":"bb-cloud-download",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Cloud",
    "symbol":"bb-cloud",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Document",
    "symbol":"bb-document",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Pencil",
    "symbol":"bb-pencil",
    "category":"Business",
    "author":"fontology",
    "keywords":"Business"
  },
  {
    "name":"Heart",
    "symbol":"bb-heart",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Camera",
    "symbol":"bb-camera-still",
    "category":"Entertainment",
    "author":"fontology",
    "keywords":"Entertainment"
  },
  {
    "name":"Video camera",
    "symbol":"bb-camera-video",
    "category":"Entertainment",
    "author":"fontology",
    "keywords":"Entertainment"
  },
  {
    "name":"Star",
    "symbol":"bb-star",
    "category":"BBUI",
    "author":"fontology",
    "keywords":"BBUI"
  },
  {
    "name":"Warning",
    "symbol":"bb-warning",
    "category":"BBUI",
    "author":"fontology",
    "keywords":"BBUI"
  },
  {
    "name":"Vimeo",
    "symbol":"bb-square-vimeo",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Twitter",
    "symbol":"bb-square-twitter",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Twitter",
    "symbol":"bb-square-twitter-bird",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Radio",
    "symbol":"bb-radio",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"Pie Chart",
    "symbol":"bb-pie-chart",
    "category":"Business",
    "author":"fontology",
    "keywords":"Business"
  },
  {
    "name":"Ring Buoy",
    "symbol":"bb-ring-buoy",
    "category":"UI",
    "author":"fontology",
    "keywords":"UI"
  },
  {
    "name":"LinkedIN",
    "symbol":"bb-square-linkedin",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"LinkedIN",
    "symbol":"bb-circle-linkedin",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Google Plus",
    "symbol":"bb-square-googleplus",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Google Plus",
    "symbol":"bb-circle-googleplus",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Pinterest",
    "symbol":"bb-square-pinterest",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Pinterest",
    "symbol":"bb-circle-pinterest",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"RSS",
    "symbol":"bb-square-rss",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"RSS",
    "symbol":"bb-circle-rss",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"YouTube",
    "symbol":"bb-square-youtube",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"YouTube",
    "symbol":"bb-circle-youtube",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Facebook",
    "symbol":"bb-square-facebook",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Facebook",
    "symbol":"bb-circle-facebook",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Flickr",
    "symbol":"bb-square-flickr",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Flickr",
    "symbol":"bb-circle-flickr",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Twitter",
    "symbol":"bb-square-twitter",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Twitter",
    "symbol":"bb-circle-twitter",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Twitter",
    "symbol":"bb-square-twitter-bird",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"Twitter",
    "symbol":"bb-circle-twitter-bird",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"FaceBook",
    "symbol":"bb-square-facebook",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  },
  {
    "name":"FaceBook",
    "symbol":"bb-circle-facebook",
    "category":"Social",
    "author":"fontology",
    "keywords":"Social"
  }
]